name: "Update README"

on:
  push: {branches: master}
  workflow_dispatch:
    #schedule:
    #- cron: "0 4 * * *"
jobs:
  octoprofile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main

      - name: "Generate README.md with octoprofile"
        run: ./octoprofile template.md -o README.md
        shell: bash

      - uses: stefanzweifel/git-auto-commit-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          commit_message: Update octoprofile-generated README
          branch: master
