name: Update README

on:
  push: {branches: master}
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  octoprofile:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master

      - uses: rderik/octoprofile-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          template: "template.md"
          output: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update octoprofile-generated README
          branch: master
